
nav:
- Home: index.md
- Projects:
  - Content/Projects/index.md
  - EasyCheckIO:
      - Intro: Content/Projects/EasyCheckIO/intro.md
      - Configurazione Plc: Content/Projects/EasyCheckIO/PlcCommunication.md
      - Creazione variabili: Content/Projects/EasyCheckIO/CreateVariable.md
      - Compilazione variabili: Content/Projects/EasyCheckIO/CompileVariables.md
      - Online: Content/Projects/EasyCheckIO/Online.md
      - Backup&Restore: Content/Projects/EasyCheckIO/BackupRestore.md
- About me: Content/About/index.md

site_name: Corlis
theme:
  name: material
  highlightjs: true
  font:
    text: Noto Sans SC
    code: Noto Sans SC
  favicon: img/kiwi.ico
  logo: img/kiwi.svg
  language: it
  features:
    - header.autohide
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link
    - search.share
    - content.code.annotation
    - content.code.copy
    - content.action.view
    - navigation.prune

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark  
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true  

extra:
  generator: false

plugins:
   - glightbox
   - offline

